spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transaction_risk_monitor
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false